### ISSUE TITLE
No errors returned

### ISSUE THREAD

**Issue by knownasilya** [jkusa/ember-arg-types#3]
I'm passing a string instead of an object, but get no errors in the console.

<img width="597" alt="Screen Shot 2020-03-25 at 11 05 58 AM" src="https://user-images.githubusercontent.com/34726/77551442-b933aa80-6e88-11ea-921c-842311159c20.png">

**Comment by jkusa** [comment]
Hey @knownasilya are you using `blog` in your template or doing a `this.blog` in your `.js` file?

**Comment by jkusa** [comment]
Hey @knownasilya, are you getting the correct value (from `this.args.blog`) passed to your `listDirectory` function?

Also, you will want to use `object.isRequired` if you want to make sure `undefined` is not a valid arg value.

**Comment by knownasilya** [comment]
I tested by passing a string to `<PostsList @blog="test"/>`

**Comment by jkusa** [comment]
@knownasilya I wonder if your `this.blog` getter is somehow not firing in your example.

Here is an example app that demonstrates an `object` arg assertion: https://github.com/jkusa/arg-types-demo/commit/f417469edfb245c7f507c57b58e6d8e340b1f8c1

Check it out and let me know if you have any questions.

**Comment by jkusa** [comment]
@knownasilya here is a [twiddle version of the demo app](https://ember-twiddle.com/71bf2611281fae94c1443f64346817e1?openFiles=templates.application%5C.hbs%2Ctemplates.components.blog-post%5C.hbs).

Let me know if you are still having issues.

**Comment by knownasilya** [comment]
My issue was the `required` vs `isRequired`.
