### ISSUE TITLE
Add support for .oneOfType()

### ISSUE THREAD

**Issue by notmessenger** [jkusa/ember-arg-types#73]
https://github.com/facebook/prop-types supports `.oneOfType()` which would be a nice addition to this add-on.

**Comment by jkusa** [comment]
Hi @notmessenger 👋 . `ember-arg-types` actually is _bring your own validators_ and does not ship any validation logic. However, it is fully compatible with `facebook/prop-types` and is the reference validation library for this project.


Here is an example of with `oneOfType` + `ember-arg-types`: [oneOfType-example](https://ember-twiddle.com/290026c0e127c907554cf13cc74c19a5?openFiles=components.test-cmp%5C.js%2C)

**Comment by notmessenger** [comment]
> Hi @notmessenger 👋 . `ember-arg-types` actually is _bring your own validators_ and does not ship any validation logic. However, it is fully compatible with `facebook/prop-types` and is the reference validation library for this project.
> 
> Here is an example of with `oneOfType` + `ember-arg-types`: [oneOfType-example](https://ember-twiddle.com/290026c0e127c907554cf13cc74c19a5?openFiles=components.test-cmp%5C.js%2C)

Thanks!

**Comment by jkusa** [comment]
No problem! To be clear, `prop-types` **is a dependency** for `ember-arg-types` and is used to execute validators. However, custom validators are supported by `prop-types`. You just need to implement their function contract. See the `customProp` example on the `prop-types` [README](https://github.com/facebook/prop-types#usage).
