### ISSUE TITLE
Code never run inside getter

### ISSUE THREAD

**Issue by GuillaumeCisco** [jkusa/ember-arg-types#8]
I've just tested this library with the classic example :

```js
import Component from '@glimmer/component';
import { arg } from 'ember-arg-types';
import { string } from 'prop-types';

export default class CharacterComponent extends Component {
  // `name` string arg that is required
  @arg(string.isRequired)
  name;
}
```
```js
{{!-- @name should be a string, not a number --}}
<CharacterComponent @name={{123}}>
```

But nothing happened.
i've put some `console.log` and it looks like this [method](https://github.com/jkusa/ember-arg-types/blob/master/addon/decorator.ts#L18) is never called.

What am I missing?

**Comment by GuillaumeCisco** [comment]
Furthermore information:

I'm only able to make the error appear if I interpolate the attribute in the template.
Calling it with `{{ this.name }}`.
But as it comes from a props, shouldn't it be `{{ @name }}` (and this does not work) as discussed [here](https://ember-learn.github.io/ember-octane-vs-classic-cheat-sheet/#component-templates__template-named)

**Comment by jkusa** [comment]
Hey @GuillaumeCisco 👋 

> I'm only able to make the error appear if I interpolate the attribute in the template.
>Calling it with {{ this.name }}.

That is correct because `@arg` does not modify the `this.args.name`. Instead, the @arg decorator maps `this.args` values to **local component properties**.

As seen in the README example:

```js
@arg(string)
sortBy = 'id';
```

Is a replacement for

```js
get sortBy() {
  const { sortBy='id' } = this.args;
  assert('`sortBy` must be a string', typeof sortBy === 'string');
  return sortBy;
}
```

In both cases, if you want the type checking and defaulting, you need to reference the local component property `{{this.sortBy}}` and not `{{@sortBy}}`.

Let me know if that clarifies things.

**Comment by GuillaumeCisco** [comment]
Yes it does, thank you.
What about dynamic attributes then?

Furthermore, shouldn't we be able to trigger errors even if we do not get the local value?
It looks more understandable to me to make the check on the declaration, not when using it.

What are your thoughts about that?

**Comment by GuillaumeCisco** [comment]
no thoughts ? 😢

**Comment by jkusa** [comment]
Hey @GuillaumeCisco just saw your previous message.

> What about dynamic attributes then?

Not sure what you mean exactly. Do you mean component arguments that are not known up front? Can you provide an example?

> Furthermore, shouldn't we be able to trigger errors even if we do not get the local value?
It looks more understandable to me to make the check on the declaration, not when using it.

When you say _check on the declaration_, do you mean checking the types when the component is given argument values? When I started on this project, I did look into checking argument types when the component is given new argument values. At the time, I didn't see great options. Glimmer does not provide a `didUpdateAttrs` like method to hook into and I didn't want to reopen the glimmer component class to add an `arguments` observer for all components. 

Ideally, if you have an argument on a component it has a purpose and that code path will be tested/exercised at some point. However, I realize code bases don't always have complete coverage :)

**Comment by GuillaumeCisco** [comment]
Thank you @jkusa for your answer.
You can read more about dynamic attributes [here](https://guides.emberjs.com/release/components/component-arguments-and-html-attributes/#toc_arguments)
```
The syntax {{@initial}} means that the contents inside the <div> tag are dynamic and will be specified by the <Avatar> tag. 
Likewise, the {{@title}} syntax means that the contents of the title attribute are dynamic and will be specified in the same
 way.
```

> When you say check on the declaration, do you mean checking the types when the component is given argument values?
Absolutely.

Currently dynamic components and not used arguments in template won't have type validation :/

I solved this issue by creating my own custom glimmer component supporting prop-types.
It is very easy:
`glimmer-proptypes.js`
```js
import GlimmerComponent from '@glimmer/component';
import { runInDebug } from '@ember/debug';
import PropTypes from 'prop-types';

class GlimmerPropTypesComponent extends GlimmerComponent {
  constructor(...args) {
    super(...args);
    if (this.constructor.propTypes) {
      runInDebug(() => {
        PropTypes.checkPropTypes(this.constructor.propTypes, this.args, 'prop', this.constructor.name);
      });
    }
  }
}

export default GlimmerPropTypesComponent;
```
use like:
```js
import Component from 'glimmer-proptypes';

class MyComponent extends Component {
    ...
}

MyComponent.propTypes = {
   foo: PropTypes.string,
};

export default MyComponent;
```

Simply inheriting from this component instead of the glimmer component makes the trick 🎉 🎉

**Comment by jkusa** [comment]
@GuillaumeCisco the `ember-arg-types` decorator creates getters that are reactive to component argument value changes (supporting dynamic argument value validation). See the following test:

https://github.com/jkusa/ember-arg-types/blob/52433ecde47d1937f0998599e43013c2e6098cf8/tests/integration/components/args-decorator-test.ts#L53-L100

First `heart` is set to `1` (line 57) and passes the number prop type check. Afterwards, `heart` is set to a string (line 74) and throws an exception (line 68).

**Comment by jkusa** [comment]
@GuillaumeCisco in your `GlimmerPropTypesComponent` it looks like you are only checking the types with the initial argument values (via the constructor). An update to the `foo` argument value will not be validated, correct?

**Comment by GuillaumeCisco** [comment]
Yes absolutely, this is the goal of propTypes

**Comment by jkusa** [comment]
@GuillaumeCisco hmm, not sure I am following you. 😄 

Earlier you mentioned the need for validating dynamic arguments (which this lib supports) and then mentioned that the _goal of propTypes_ is to only validate the initial values. When using prop-types with React, every prop value, whether initial or updated, will be validated.

All this being said, I think what you are after is **eager validation**.

Currently, this library only supports validation of accessed arguments or **lazy validation**. This is mainly due to the use of decorators that declaratively configure both validations and default values that use Ember's pull based reactive model.

If my assumption is correct about what you are after (and you wish to use this library 😄 ) , let's close this ticket and open a new issue for adding support for eager argument validation.

**Comment by GuillaumeCisco** [comment]
Thank you @jkusa for you answer.
It looks like you did not understand what is a dynamic attribute from the ember doc.
A dynamic attribute comes from the parent component and is prefixed with `@`, this library does not deal with it.
Please see my second comment in this thread.

I will close this issue.
